import { chatComplete, isEmbeddingAvailable, getEmbedding, getQueryEmbedding, cosineSimilarity } from './openai.js'
import db from '../db.js'

// Allowed fields for SQL conditions generated by LLM
const ALLOWED_FIELDS = new Set(['session_date', 'dissatisfaction_info', 'bot_conversation', 'human_conversation', 'user_id', 'sequence_num'])
const ALLOWED_OPERATORS = new Set(['=', '!=', '>', '<', '>=', '<=', 'LIKE', 'IS NOT NULL', 'IS NULL', 'NOT LIKE'])

interface SQLCondition {
  field: string
  operator: string
  value?: string
}

/**
 * Step 1: LLM parses scenario description into:
 *  - semantic_query: the part that needs semantic matching against summary_text
 *  - sql_conditions: structured conditions that can be expressed as SQL WHERE
 */
async function parseScenarioDescription(description: string): Promise<{
  semanticQuery: string
  conditions: SQLCondition[]
}> {
  const prompt = `你是一个数据分析专家。用户描述了一个想要分析的客服会话场景。
请将描述拆解为两部分：

1. semantic_query: 需要语义匹配的部分（关于对话内容、买家诉求、客服表现等）
2. sql_conditions: 可以转换为SQL条件的结构化部分

可用字段：
- session_date (TEXT, 格式 'YYYY-MM-DD'): 会话日期
- dissatisfaction_info (TEXT): 不满意信息，非空字符串表示买家表达了不满
- bot_conversation (TEXT): AI客服对话内容
- human_conversation (TEXT): 人工客服对话内容

可用操作符：=, !=, >, <, >=, <=, LIKE, IS NOT NULL, IS NULL, NOT LIKE

返回JSON（不要输出其他内容）：
{
  "semantic_query": "需要语义匹配的自然语言描述",
  "sql_conditions": [
    { "field": "字段名", "operator": "操作符", "value": "值" }
  ]
}

规则：
- semantic_query 是必须的，至少包含场景的核心语义描述
- 如果描述中没有可提取的结构化条件，sql_conditions 返回空数组
- IS NOT NULL / IS NULL 操作符不需要 value
- LIKE 操作符的 value 用 % 做通配符
- 日期条件用 session_date 字段
- "有不满意" → dissatisfaction_info IS NOT NULL 且 dissatisfaction_info != ''
- "有人工对话" → human_conversation IS NOT NULL 且 human_conversation != ''`

  try {
    const raw = await chatComplete(prompt, description)
    const jsonStr = raw.replace(/```json\s*/g, '').replace(/```\s*/g, '').replace(/<think>[\s\S]*?<\/think>/g, '').trim()
    const parsed = JSON.parse(jsonStr)
    return {
      semanticQuery: parsed.semantic_query || description,
      conditions: Array.isArray(parsed.sql_conditions) ? parsed.sql_conditions : [],
    }
  } catch {
    // If LLM parsing fails, use the full description as semantic query
    return { semanticQuery: description, conditions: [] }
  }
}

/**
 * Build validated SQL WHERE clause from LLM-generated conditions.
 * Only allows whitelisted fields and operators to prevent injection.
 */
function buildSQLWhere(conditions: SQLCondition[]): { where: string; params: string[] } {
  let where = ''
  const params: string[] = []

  for (const cond of conditions) {
    if (!ALLOWED_FIELDS.has(cond.field)) continue
    if (!ALLOWED_OPERATORS.has(cond.operator.toUpperCase())) continue

    const op = cond.operator.toUpperCase()
    if (op === 'IS NOT NULL' || op === 'IS NULL') {
      where += ` AND s.${cond.field} ${op}`
    } else {
      where += ` AND s.${cond.field} ${op} ?`
      params.push(cond.value || '')
    }
  }

  return { where, params }
}

/**
 * Semantic matching against summary_text only.
 * Returns session IDs sorted by relevance.
 */
async function semanticMatchSummaries(
  query: string,
  rows: { session_id: string; summary_text: string; embedding: string | null }[]
): Promise<string[]> {
  const hasEmbeddings = isEmbeddingAvailable() && rows.some(r => r.embedding)

  if (hasEmbeddings) {
    const queryVec = await getQueryEmbedding(query)
    const scored = rows
      .filter(r => r.embedding)
      .map(row => ({
        sessionId: row.session_id,
        similarity: cosineSimilarity(queryVec, JSON.parse(row.embedding!)),
        summary: (row.summary_text || '').slice(0, 40),
      }))
      .sort((a, b) => b.similarity - a.similarity)

    // Log score distribution
    const scores = scored.map(r => r.similarity.toFixed(3))
    console.log(`[Matcher] All scores: [${scores.join(', ')}]`)

    // Dynamic threshold based on score distribution
    const sims = scored.map(r => r.similarity)
    const mean = sims.reduce((a, b) => a + b, 0) / sims.length
    const std = Math.sqrt(sims.reduce((a, b) => a + (b - mean) ** 2, 0) / sims.length)
    const dynamicThreshold = Math.max(mean + 1.0 * std, 0.5) // floor at 0.5
    const matched = scored.filter(r => r.similarity >= dynamicThreshold)
    console.log(`[Matcher] mean=${mean.toFixed(3)}, std=${std.toFixed(3)}, threshold=${dynamicThreshold.toFixed(3)}, matched=${matched.length}/${scored.length}`)
    return matched.map(r => r.sessionId)
  }

  // Fallback: keyword expansion + text matching on summary_text only
  let expandedTerms: string[] = []
  try {
    const raw = await chatComplete(
      `你是搜索关键词扩展专家。将用户搜索意图扩展为短关键词JSON数组。
要求：
- 每个关键词2-4个中文字符或一个英文单词
- 不要长短语，只要原子级别的短词
- 不要通用词如"买家""客服""对话""问题""服务"，要有区分度的词
- 覆盖中英文同义词
- 10-20个关键词
只返回JSON数组，不要其他文字。`,
      query
    )
    const jsonStr = raw.replace(/```json\s*/g, '').replace(/```\s*/g, '').replace(/<think>[\s\S]*?<\/think>/g, '').trim()
    const parsed = JSON.parse(jsonStr)
    if (Array.isArray(parsed)) expandedTerms = parsed.map((t: string) => t.toLowerCase())
    console.log(`[Matcher] Expanded terms for "${query}":`, expandedTerms)
  } catch (e: any) {
    console.warn(`[Matcher] Keyword expansion failed:`, e.message)
  }

  // If LLM expansion failed, extract meaningful terms from query (skip common words)
  const commonWords = new Set(['买家', '客服', '对话', '问题', '服务', '会话', '用户', '人工', '智能', '分析', '平台', '全量', '帮我', '涉及', '相关', '各种', '什么', '所有', '场景', '过程'])
  if (expandedTerms.length === 0) {
    const fallbackTerms = query
      .split(/[\s,，、。；;：:!！?？]+/)
      .filter(t => t.length >= 2 && t.length <= 4 && !commonWords.has(t))
      .map(t => t.toLowerCase())
    expandedTerms = [...new Set(fallbackTerms)]
  }

  console.log(`[Matcher] Terms: ${expandedTerms.length} | Rows: ${rows.length}`)

  // Minimum 2 keyword matches required to be considered a match
  const MIN_MATCHES = 2

  return rows
    .map(row => {
      const text = (row.summary_text || '').toLowerCase()
      let matchCount = 0
      for (const term of expandedTerms) {
        if (term && text.includes(term)) matchCount++
      }
      return { sessionId: row.session_id, matchCount, similarity: Math.min(Math.round(matchCount * 0.12 * 100) / 100, 1.0) }
    })
    .filter(r => r.matchCount >= MIN_MATCHES)
    .sort((a, b) => b.matchCount - a.matchCount)
    .map(r => r.sessionId)
}

/**
 * Main entry: match a scenario against all sessions.
 * Two-step filtering:
 *   1. Semantic match on summary_text
 *   2. SQL conditions on structured fields
 *
 * The SQL conditions are applied first (they narrow down the candidate set),
 * then semantic matching is done on the filtered set.
 */
export async function matchScenario(scenarioId: string): Promise<{ matchedCount: number }> {
  const scenario = db.prepare('SELECT * FROM scenarios WHERE id = ?').get(scenarioId) as any
  if (!scenario) throw new Error('Scenario not found')

  // Mark as matching
  db.prepare("UPDATE scenarios SET match_status = 'matching', error_message = '' WHERE id = ?").run(scenarioId)

  try {
    // Step 1: Parse description into semantic query + SQL conditions
    const { semanticQuery, conditions } = await parseScenarioDescription(scenario.description)
    const { where: sqlWhere, params: sqlParams } = buildSQLWhere(conditions)

    console.log(`[Matcher] Scenario "${scenario.name}": semanticQuery="${semanticQuery}", sqlConditions=${JSON.stringify(conditions)}, sqlWhere="${sqlWhere}"`)

    // Build query: get sessions with summaries, applying SQL filters
    let sql = `
      SELECT ss.session_id, ss.summary_text, ss.embedding
      FROM session_summaries ss
      JOIN sessions s ON s.id = ss.session_id
      WHERE 1=1
    `
    const params: string[] = []

    // Scenario-level date range (from the form fields)
    if (scenario.date_from) { sql += ' AND s.session_date >= ?'; params.push(scenario.date_from) }
    if (scenario.date_to) { sql += ' AND s.session_date <= ?'; params.push(scenario.date_to) }

    // LLM-generated SQL conditions (second filter applied at query level for efficiency)
    if (sqlWhere) {
      sql += sqlWhere
      params.push(...sqlParams)
    }

    let rows = db.prepare(sql).all(...params) as any[]
    console.log(`[Matcher] SQL query returned ${rows.length} rows (with SQL conditions)`)

    // If SQL conditions filtered out everything, retry without them
    // (semantic matching alone may be sufficient)
    if (rows.length === 0 && sqlWhere) {
      console.log(`[Matcher] Retrying without SQL conditions...`)
      let baseSql = `
        SELECT ss.session_id, ss.summary_text, ss.embedding
        FROM session_summaries ss
        JOIN sessions s ON s.id = ss.session_id
        WHERE 1=1
      `
      const baseParams: string[] = []
      if (scenario.date_from) { baseSql += ' AND s.session_date >= ?'; baseParams.push(scenario.date_from) }
      if (scenario.date_to) { baseSql += ' AND s.session_date <= ?'; baseParams.push(scenario.date_to) }
      rows = db.prepare(baseSql).all(...baseParams) as any[]
      console.log(`[Matcher] Without SQL conditions: ${rows.length} rows`)
    }

    // Step 2: Semantic matching on summary_text (first filter)
    const matchedSessionIds = await semanticMatchSummaries(semanticQuery, rows)

    // Save results
    db.prepare("UPDATE scenarios SET matched_session_ids = ?, matched_count = ?, match_status = 'completed' WHERE id = ?")
      .run(JSON.stringify(matchedSessionIds), matchedSessionIds.length, scenarioId)

    return { matchedCount: matchedSessionIds.length }
  } catch (err: any) {
    db.prepare("UPDATE scenarios SET match_status = 'failed', error_message = ? WHERE id = ?")
      .run(err.message || 'Unknown error', scenarioId)
    throw err
  }
}
